version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: "rcj-cms-nginx"
    ports:
      - 3000:80
      #- 80:80
      #- 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- /etc/letsencrypt:/etc/letsencrypt
      - ./data/public:/opt/rcj-cms/public
      - ./logs:/opt/rcj-cms/logs
      - ./conf/nginx/errorPage:/etc/nginx/html/customError
    depends_on: 
      - rcj-cms
    restart: always

  rcj-cms:
    image: ryorobo/rcj-cms:latest
    container_name: "rcj-cms-node"
    depends_on: 
      - mongo
      - redis
    volumes:
      - ./data/documents:/opt/rcj-cms/documents
      - ./data/cabinet:/opt/rcj-cms/cabinet
      - ./data/survey:/opt/rcj-cms/survey
      - ./conf/rcj-cms/leagues.json:/opt/rcj-cms/leagues.json
      - ./conf/rcj-cms/process.env:/opt/rcj-cms/process.env
      - ./data/templates:/opt/rcj-cms/templates
      - ./data/fonts:/opt/rcj-cms/fonts
      - ./logs:/opt/rcj-cms/logs
      - ./data/public:/opt/rcj-cms/sharePublic
      - ./data/tmp:/opt/rcj-cms/tmp
    command: >
      sh -c 'cp -f -r /opt/rcj-cms/public/* /opt/rcj-cms/sharePublic &&
      node server.js'
    restart: always


  mongo:
    image: mongo:latest
    container_name: "rcj-cms-mongo"
    command: 
      - mongod
    volumes:
      - ./data/db:/data/db
    restart: always


  redis:
    image: "redis:latest"
    container_name: "rcj-cms-redis"
    volumes:
      - "./data/redis:/data"
    restart: always